services:
  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: onsell_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onsell
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-postgres-init:/docker-entrypoint-initdb.d
    networks:
      - onsell_network

  # Redis
  redis:
    image: redis:7
    container_name: onsell_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - onsell_network

networks:
  onsell_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: