version: '3.9'

services:
  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: onsell_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: onsell,evolution
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-postgres-init:/docker-entrypoint-initdb.d
    networks:
      - onsell_network

  # Redis
  redis:
    image: redis:7
    container_name: onsell_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - onsell_network

  # Evolution API (WhatsApp)
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SERVER_TYPE: http
      SERVER_PORT: 8080
      SERVER_URL: http://localhost:8080
      CORS_ORIGIN: "*"
      CORS_METHODS: GET,POST,PUT,DELETE
      CORS_CREDENTIALS: "true"
      
      LOG_LEVEL: ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET
      LOG_COLOR: "true"
      LOG_BAILEYS: error
      
      EVENT_EMITTER_MAX_LISTENERS: 50
      
      DEL_INSTANCE: "false"
      
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://postgres:postgres@postgres:5432/evolution?schema=public
      DATABASE_CONNECTION_CLIENT_NAME: evolution_exchange
      
      DATABASE_SAVE_DATA_INSTANCE: "true"
      DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
      DATABASE_SAVE_MESSAGE_UPDATE: "true"
      DATABASE_SAVE_DATA_CONTACTS: "true"
      DATABASE_SAVE_DATA_CHATS: "true"
      DATABASE_SAVE_DATA_LABELS: "true"
      DATABASE_SAVE_DATA_HISTORIC: "true"
      DATABASE_SAVE_IS_ON_WHATSAPP: "true"
      DATABASE_SAVE_IS_ON_WHATSAPP_DAYS: 7
      DATABASE_DELETE_MESSAGE: "true"
      
      WEBHOOK_GLOBAL_ENABLED: "true"
      WEBHOOK_GLOBAL_URL: http://host.docker.internal:8000/api/webhooks/whatsapp
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: "false"
      
      WEBHOOK_EVENTS_QRCODE_UPDATED: "true"
      WEBHOOK_EVENTS_MESSAGES_SET: "true"
      WEBHOOK_EVENTS_MESSAGES_UPSERT: "true"
      WEBHOOK_EVENTS_MESSAGES_EDITED: "true"
      WEBHOOK_EVENTS_MESSAGES_UPDATE: "true"
      WEBHOOK_EVENTS_MESSAGES_DELETE: "true"
      WEBHOOK_EVENTS_SEND_MESSAGE: "true"
      WEBHOOK_EVENTS_CONTACTS_SET: "true"
      WEBHOOK_EVENTS_CONTACTS_UPSERT: "true"
      WEBHOOK_EVENTS_CONTACTS_UPDATE: "true"
      WEBHOOK_EVENTS_PRESENCE_UPDATE: "true"
      WEBHOOK_EVENTS_CHATS_SET: "true"
      WEBHOOK_EVENTS_CHATS_UPSERT: "true"
      WEBHOOK_EVENTS_CHATS_UPDATE: "true"
      WEBHOOK_EVENTS_CHATS_DELETE: "true"
      WEBHOOK_EVENTS_GROUPS_UPSERT: "true"
      WEBHOOK_EVENTS_GROUPS_UPDATE: "true"
      WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE: "true"
      WEBHOOK_EVENTS_CONNECTION_UPDATE: "true"
      
      CONFIG_SESSION_PHONE_CLIENT: Evolution API
      CONFIG_SESSION_PHONE_NAME: Chrome
      CONFIG_SESSION_PHONE_VERSION: 2.3000.1015901307
      
      QRCODE_LIMIT: 30
      QRCODE_COLOR: "#175197"
      
      AUTHENTICATION_API_KEY: 429683C4C977415CAAFCCE10F7D57E11
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: "true"
      
      LANGUAGE: pt
      
      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: redis://redis:6379/6
      CACHE_REDIS_TTL: 604800
      CACHE_REDIS_PREFIX_KEY: evolution
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - onsell_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - redis

networks:
  onsell_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  evolution_instances: 