version: '3'

services:
  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: onsell_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: onsell
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - onsell_network

  # Redis
  redis:
    image: redis:7
    container_name: onsell_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - onsell_network

  # Evolution API (WhatsApp)
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: onsell_evolution_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - evolution_api_data:/evolution/instances
    environment:
      - SERVER_URL=http://localhost:8080
      - CORS_ORIGIN=*
      - LOG_LEVEL=ERROR
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=your-api-key-here
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - WEBHOOK_GLOBAL_URL=http://host.docker.internal:8000/api/webhooks/whatsapp
      - WEBHOOK_GLOBAL_ENABLED=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - onsell_network

networks:
  onsell_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  evolution_api_data: 