services:
  db:
    image: postgres:15
    container_name: onsell_db_local
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    networks:
      - onsell-network

networks:
  onsell-network:
    driver: bridge

volumes:
  postgres_data_local: 